import './map.js';
import './password-strength.js';
import './user-menu.js';
import './backoffice.js';
import './capteurs.js';
import './points.js';
import './campagnes-gestion.js';
import './campagne.js';
import './join-session.js';
